basePath: /api/v1
definitions:
  models.User:
    properties:
      country_code:
        type: string
      created_at:
        type: string
      id:
        type: string
      is_verified:
        type: boolean
      last_login_at:
        type: string
      mobile_number:
        type: string
      roles:
        items:
          type: string
        type: array
      updated_at:
        type: string
    required:
    - country_code
    - mobile_number
    type: object
  models.UserRegistration:
    properties:
      country_code:
        type: string
      mobile_number:
        type: string
      otp_code:
        type: string
      password:
        maxLength: 72
        minLength: 8
        type: string
    required:
    - country_code
    - mobile_number
    - otp_code
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: User management microservice
  title: GreenEye User Management API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      description: Register a new user in the system
      parameters:
      - description: User Creation Details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRegistration'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Create a new user
      tags:
      - users
schemes:
- http
- https
swagger: "2.0"
